export const TRASH_PATTERNS = [
  /^BP_Soldier_/,
  /^BP_DeveloperAdminCam/,
  /_Destroy$/,
  /_Destroy_/,
  /_destroyed$/,
  /_destroyed_/,
  /_Destroyed$/,
  /_Destroyed_/,
  /_Burn$/,
  /_Burn_/,
  /_Burned$/,
  /_Burned_/,
  /_Obliterate$/i,
  /_Obliterate_/i,
  /_Obliterated/i,
  /_Crash$/,
  /_Crash_/,
  /_Ammocook$/,
  /_Ammocook_/,
  /_AmmoCook$/,
  /_AmmoCook_/,
  /_Knockedout$/,
  /_Knockedout_/,
  /_wreck/,
  /^BP_Kamaz_5350_Logi/,
  /^BP_Ural_375_Logi/,
  /^BP_Technical4Seater_Logi/,
  /^BP_Technical4Seater_Transport/,
  /^BP_Armored_Technical4Seater_Transport/,
  /^BP_Armored_Technical4Seater_Logi/,
  /^BP_Armored_Ural_375_Logi/,
  /^BP_US_Util_/,
  /^BP_CAF_Util_/,
  /^BP_Brit_Util_Truck/,
  /^BP_Aussie_Util_Truck/,
  /^BP_TLF_Util_Truck/,
  /^BP_WPMC_Util_/,
  /^BP_CTM131_Logistic/,
  /^BP_Minsk/,
  /^BP_Quadbike/,
  /^BP_RHIB_Logistics/,
  /^BP_Kraz_6322_Logi/,
  /^BP_Kraz_6322$/,
  /^BP_MTLB_LOGI_/,
  /^BP_AAVP7A1_Logi/,
  /^BP_AAVP7A1_Woodland_Logi/,
  /^BP_LUVW_Logi/,
  /^BP_M113A3_Logistics/,
  /^BP_ZSD05_Logi/,
  /^BP_Ural_4320_logi/,
  /^BP_Ural_4320_GFI$/,
  /^BP_CPV_Transport/,
  /^BP_LPPV$/,
  /^BP_LPPV_Woodland$/,
  /^BP_Technical_Logi_INS/,
  /^BP_Technical_Transport_INS/,
  /^BP_BTR_Passenger/,
  /^BP_BTR-D_PassengerCupola/,
  /^BP_FV510_Passenger/,
  /^BP_BMP2_Passenger/,
  /^BP_AAVP7A1_Passenger/,
  /^BP_LAV25_Passenger/,
  /^BP_FlyingDrone/,
  /^BP_Loach_KOTH$/,
  /^BP$/,
  /^MI8_/,
  /^UH60M_/,
  /^UH1[HY]_/,
  /^SA330_/,
  /^MRH90_/,
  /^CH146_/,
  /^Raven_/,
  /^Loach_Destroyed/,
  /^Loach_Crash/,
  /^Z8G_/,
  /^stryker_/,
  /^T72_/,
  /^T62_/,
  /^T72AV_/,
  /^T64BM2_/,
  /^BMP[123]_/,
  /^BMP1TS_/,
  /^BMD[14]M?_/,
  /^btr_/,
  /^brdm2_/,
  /^BTR-/,
  /^2a6_/,
  /^M1a[12]_/,
  /^M1a1_/,
  /^Bradley_/,
  /^Warrior_/,
  /^Scimitar_/,
  /^FV4034_/,
  /^M60T_/,
  /^M1117_Destroy/,
  /^M1128_Knockedout/,
  /^Sprut_/,
  /^ZTZ99_/,
  /^ZBD0[45]A?_/,
  /^ZBL08_/,
  /^ZTD05_/,
  /^ZSL-10_/,
  /^Zsl-10_/,
  /^LAV25_/,
  /^lav6_/,
  /^ASLAV_/,
  /^Coyote_Burn/,
  /^Safir_/,
  /^Tigr_/,
  /^PMV_destroyed/,
  /^MATV_/,
  /^M1151_/,
  /^TAPV_destroyed/,
  /^FV432_/,
  /^CSK_destroyed/,
  /^CTM131_/,
  /^LUVW_/,
  /^LPPV_Destroyed/,
  /^LPPV_Woodland_Destroyed/,
  /^PARS3_/,
  /^ACV15_/,
  /^ACV_M252_HE/,
  /^Cobra2?_Destroyed/,
  /^CPV_Destroyed/,
  /^CPV_Obliterate/,
  /^RHIB_Destroyed/,
  /^TLAV_Burn/,
  /^TLAV_destroyed/,
  /^IFV25_Ammocook/,
  /^kamaz_/,
  /^ural375_/,
  /^ural4320_/,
  /^kraz_/,
  /^BM21_.*Destroyed/,
  /^Technical_/,
  /^US_Util_/,
  /^CAF_Util_/,
  /^BritUtilTruck_/,
  /^AUS_Utility_/,
  /^TLFUtilTruck_/,
  /^WPMC_/,
];

function isTrash(key) {
  return TRASH_PATTERNS.some((p) => p.test(key));
}

const WEAPON_RULES = [
  [
    /^BP_Projectile_155mm_Artillery/,
    "Артиллерия",
    "artillery.png",
    "vehicle_arty",
  ],
  [/^BP_Heavy_Mortarround/, "Миномёт 120мм", "mortar120.png", "mortar"],
  [/^BP_Mortarround_120mm/, "Миномёт 120мм", "mortar120.png", "mortar"],
  [/^BP_Mortarround4/, "Миномёт 82мм", "mortarround4.png", "mortar"],
  [/^BP_BM21_Rocket_Proj/, "БМ-21 Град", "bm21.png", "vehicle_arty"],
  [/^BP_BM21Grad_Weapon/, "БМ-21 Град", "bm21.png", "vehicle_arty"],
  [/^BP_M1064A3_MortarTurret/, "M1064 Миномёт", "mortar120.png", "mortar"],
  [
    /^BP_Technical_MortarTurret/,
    "Техничка Миномёт",
    "mortarround4.png",
    "mortar",
  ],
  [
    /^BP_Technical_M252mortar/,
    "Техничка Миномёт",
    "mortarround4.png",
    "mortar",
  ],
  [/^BP_Projectile_Hell_Cannon/, "Адская Пушка", "hellcannon.png", "mortar"],
  [
    /^BP_Projectile_125mm_Frag/,
    "Танк 125мм ОФС",
    "tank_frag.png",
    "vehicle_cannon",
  ],
  [
    /^BP_Projectile_125mm_HEAT/,
    "Танк 125мм Кум.",
    "tank_heat.png",
    "vehicle_cannon",
  ],
  [
    /^BP_Projectile_120mm_HEAT/,
    "Танк 120мм Кум.",
    "tank_heat.png",
    "vehicle_cannon",
  ],
  [
    /^BP_Projectile_115mm_HEAT/,
    "Танк 115мм Кум.",
    "tank_heat.png",
    "vehicle_cannon",
  ],
  [
    /^BP_Projectile_100mm_Frag/,
    "Спрут 100мм ОФС",
    "tank_frag.png",
    "vehicle_cannon",
  ],
  [
    /^BP_Projectile_76mm_HEAT/,
    "БТР-Д 76мм Кум.",
    "tank_heat.png",
    "vehicle_cannon",
  ],
  [
    /^BP_Projectile_76mm_Frag/,
    "БТР-Д 76мм ОФС",
    "tank_frag.png",
    "vehicle_cannon",
  ],
  [
    /^BP_Projectile_76mm_Smoke/,
    "БТР-Д 76мм Дым",
    "tank_smoke.png",
    "vehicle_cannon",
  ],
  [/^BP_M256A1_AP/, "M256 БПС", "tank_sabot.png", "vehicle_cannon"],
  [/^BP_M256A1_HEAT/, "M256 Кум.", "tank_heat.png", "vehicle_cannon"],
  [/^BP_M256A1_coax/, "M256 Спарка", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_L55_AP/, "L55 БПС", "tank_sabot.png", "vehicle_cannon"],
  [/^BP_L55_HEAT/, "L55 Кум.", "tank_heat.png", "vehicle_cannon"],
  [/^BP_L55_coax/, "L55 Спарка", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_L30A1_AP/, "L30A1 БПС", "tank_sabot.png", "vehicle_cannon"],
  [/^BP_L30A1_HESH/, "L30A1 HESH", "tank_heat.png", "vehicle_cannon"],
  [/^BP_L94A1_coax/, "L94A1 Спарка", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_2A46_AP/, "2A46 БПС", "tank_sabot.png", "vehicle_cannon"],
  [/^BP_2A46_HEAT/, "2A46 Кум.", "tank_heat.png", "vehicle_cannon"],
  [/^BP_2A46_Frag/, "2A46 ОФС", "tank_frag.png", "vehicle_cannon"],
  [/^BP_2A46_coax/, "2A46 Спарка", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_2A46_T72AV_AP/, "2A46 Т-72АВ БПС", "tank_sabot.png", "vehicle_cannon"],
  [
    /^BP_2A46_T72AV_coax/,
    "2A46 Т-72АВ Спарка",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_2A46_T72A_AP/, "2A46 Т-72А БПС", "tank_sabot.png", "vehicle_cannon"],
  [
    /^BP_2A46_T72A_coax/,
    "2A46 Т-72А Спарка",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_2A46M_AP/, "2А46М БПС", "tank_sabot.png", "vehicle_cannon"],
  [/^BP_2A46M_HEAT/, "2А46М Кум.", "tank_heat.png", "vehicle_cannon"],
  [/^BP_2A46M_Frag/, "2А46М ОФС", "tank_frag.png", "vehicle_cannon"],
  [/^BP_2A46M_coax/, "2А46М Спарка", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_ZPT-98_AP/, "ZPT-98 БПС", "tank_sabot.png", "vehicle_cannon"],
  [/^BP_ZPT-98_HEAT/, "ZPT-98 Кум.", "tank_heat.png", "vehicle_cannon"],
  [/^BP_ZPT-98_HE/, "ZPT-98 ОФС", "tank_frag.png", "vehicle_cannon"],
  [/^BP_ZPT-98_coax/, "ZPT-98 Спарка", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_MG253_AP/, "MG253 БПС", "tank_sabot.png", "vehicle_cannon"],
  [/^BP_MG253_Frag/, "MG253 ОФС", "tank_frag.png", "vehicle_cannon"],
  [/^BP_MG253_coax/, "MG253 Спарка", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_M68A2_AP/, "M68A2 БПС", "tank_sabot.png", "vehicle_cannon"],
  [/^BP_M68A2_HEAT/, "M68A2 Кум.", "tank_heat.png", "vehicle_cannon"],
  [/^BP_M68A2_coax/, "M68A2 Спарка", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_2A20_AP/, "2A20 БПС", "tank_sabot.png", "vehicle_cannon"],
  [/^BP_2A20_Frag/, "2A20 ОФС", "tank_frag.png", "vehicle_cannon"],
  [/^BP_2A20_coax/, "2A20 Спарка", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_M1A1_FLEX_M2/, "M1A1 M2", "m2browning.png", "vehicle_mg"],
  [/^BP_M1A1_USMC_Cmdr_M2/, "M1A1 Командир M2", "m2browning.png", "vehicle_mg"],
  [
    /^BP_M240_Loaders/,
    "M240 Заряжающий",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_T90A_Kord_Cupola/, "Т-90А КОРД", "kord.png", "vehicle_mg"],
  [/^BP_T72AV_Kord_Cupola/, "Т-72АВ КОРД", "kord.png", "vehicle_mg"],
  [/^BP_Kord_Cupola_T72/, "Т-72 КОРД", "kord.png", "vehicle_mg"],
  [/^BP_M60T_M85/, "M60T M85", "m2browning.png", "vehicle_mg"],
  [/^BP_Cupola_Dshk/, "ДШК Купола", "dshk.png", "vehicle_mg"],
  [/^BP_Sprut_RWS_PKT/, "Спрут ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_2A45_AP/, "2А45 БПС", "tank_sabot.png", "vehicle_cannon"],
  [/^BP_2A45_coax/, "2А45 Спарка", "coaxialmachinegun.png", "vehicle_mg"],
  [
    /^BP_Projectile_30mm_HE_Red_Rarden/,
    "Rarden 30мм",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [
    /^BP_Projectile_30mm_HE_Red/,
    "30мм ОФ (красн.)",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [
    /^BP_Projectile_30mm_HE_Green/,
    "30мм ОФ (зел.)",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [/^BP_Projectile_30mm_HE$/, "30мм ОФ", "30mm_he.png", "vehicle_cannon"],
  [/^BP_Projectile_30mm_CAS/, "30мм КАС", "30mm_ap.png", "vehicle_cannon"],
  [/^BP_Projectile_40mm_GPR/, "40мм ОФ", "40mmhedp.png", "vehicle_cannon"],
  [
    /^BP_Projectile_23mm_HE_Green/,
    "23мм ОФ (зел.)",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [/^BP_Projectile_23mm_HE/, "23мм ОФ", "30mm_he.png", "vehicle_cannon"],
  [
    /^BP_BTR82A_RUS_2A72_AP/,
    "БТР-82А 2А72 БПС",
    "30mm_ap.png",
    "vehicle_cannon",
  ],
  [
    /^BP_BTR82A_RUS_2A72_HE/,
    "БТР-82А 2А72 ОФ",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [/^BP_BTR82A_PKT/, "БТР-82А ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_BMP2_2A42_AP/, "БМП-2 2A42 БПС", "30mm_ap.png", "vehicle_cannon"],
  [/^BP_BMP2_2A42_HE/, "БМП-2 2A42 ОФ", "30mm_he.png", "vehicle_cannon"],
  [/^BP_BMP2_PKT/, "БМП-2 ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_BMP2_MEA_2A42_AP/, "БМП-2 MEA БПС", "30mm_ap.png", "vehicle_cannon"],
  [/^BP_BMP2_MEA_PKT/, "БМП-2 MEA ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_BMP2_GFI_2A42_AP/, "БМП-2 GFI БПС", "30mm_ap.png", "vehicle_cannon"],
  [/^BP_BMP2_GFI_PKT/, "БМП-2 GFI ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_BMP2M_2A42_AP/, "БМП-2М 2А42 БПС", "30mm_ap.png", "vehicle_cannon"],
  [/^BP_BMP2M_PKT/, "БМП-2М ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_BMP1_PKT/, "БМП-1 ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_BMP1TS_ZTM1_AP/, "БМП-1ТС ЗТМ-1", "30mm_ap.png", "vehicle_cannon"],
  [/^BP_BMP1TS_KT762/, "БМП-1ТС ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [
    /^BP_Technical_BMP1_PKT/,
    "Техничка БМП-1 ПКТ",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_BMD4M_2A72_AP/, "БМД-4М 2А72 БПС", "30mm_ap.png", "vehicle_cannon"],
  [/^BP_BMD4M_2A72_HE/, "БМД-4М 2А72 ОФ", "30mm_he.png", "vehicle_cannon"],
  [
    /^BP_BMD4M_2A70_HEFrag/,
    "БМД-4М 2А70 ОФ",
    "tank_frag.png",
    "vehicle_cannon",
  ],
  [
    /^BP_BMD4M_2A70_coax/,
    "БМД-4М Спарка",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [
    /^BP_BMD1M_Bow_PKT/,
    "БМД-1 Курсовой ПКТ",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_BMD1M_PKT/, "БМД-1 ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_BMP3M_2A72_AP/, "БМП-3М 2А72 БПС", "30mm_ap.png", "vehicle_cannon"],
  [
    /^BP_BMP3M_2A70_HEFrag/,
    "БМП-3М 2А70 ОФ",
    "tank_frag.png",
    "vehicle_cannon",
  ],
  [
    /^BP_BMP3M_2A70_coax/,
    "БМП-3М Спарка",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_BTR4_ZTM1_AP/, "БТР-4 ЗТМ-1 БПС", "30mm_ap.png", "vehicle_cannon"],
  [/^BP_BTR4_KT762/, "БТР-4 ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_KBA3_coax/, "КБА-3 Спарка", "coaxialmachinegun.png", "vehicle_mg"],
  [
    /^(BP_)?LAV25_M252_AP/,
    "LAV-25 Бушмастер БПС",
    "30mm_ap.png",
    "vehicle_cannon",
  ],
  [
    /^(BP_)?LAV25_M252_HE/,
    "LAV-25 Бушмастер ОФ",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [/^(BP_)?LAV25_762/, "LAV-25 7.62", "coaxialmachinegun.png", "vehicle_mg"],
  [/^(BP_)?LAV_M252_AP/, "LAV Бушмастер БПС", "30mm_ap.png", "vehicle_cannon"],
  [/^(BP_)?LAV_M252_HE/, "LAV Бушмастер ОФ", "30mm_he.png", "vehicle_cannon"],
  [/^BP_LAV_762/, "LAV 7.62", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_LAV_RWS_C6/, "LAV RWS C6", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_CROWS_C6_LAV/, "LAV CROWS C6", "coaxialmachinegun.png", "vehicle_mg"],
  [
    /^(BP_)?Coyote_M252_AP/,
    "Coyote Бушмастер БПС",
    "30mm_ap.png",
    "vehicle_cannon",
  ],
  [
    /^(BP_)?Coyote_M252_HE/,
    "Coyote Бушмастер ОФ",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [/^BP_Coyote_762/, "Coyote 7.62", "coaxialmachinegun.png", "vehicle_mg"],
  [
    /^(BP_)?ASLAV_M252_AP/,
    "ASLAV Бушмастер БПС",
    "30mm_ap.png",
    "vehicle_cannon",
  ],
  [
    /^(BP_)?ASLAV_M252_HE/,
    "ASLAV Бушмастер ОФ",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [/^(BP_)?ASLAV_762/, "ASLAV 7.62", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_Mag58_Bushmaser/, "ASLAV Mag58", "mag58.png", "vehicle_mg"],
  [
    /^(BP_)?BFV_M252_AP/,
    "Bradley Бушмастер БПС",
    "30mm_ap.png",
    "vehicle_cannon",
  ],
  [
    /^(BP_)?BFV_M252_HE/,
    "Bradley Бушмастер ОФ",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [/^BP_BFV_762/, "Bradley 7.62", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_BGM71TOWBFV_Proj/, "Bradley TOW", "bgm71_tow.png", "vehicle_atgm"],
  [/^(BP_)?ACV_M252_AP/, "ACV Бушмастер БПС", "30mm_ap.png", "vehicle_cannon"],
  [/^(BP_)?ACV_M252_HE/, "ACV Бушмастер ОФ", "30mm_he.png", "vehicle_cannon"],
  [/^BP_ACV_762/, "ACV 7.62", "coaxialmachinegun.png", "vehicle_mg"],
  [
    /^(BP_)?IFV25_M252_AP/,
    "IFV-25 Бушмастер БПС",
    "30mm_ap.png",
    "vehicle_cannon",
  ],
  [
    /^(BP_)?IFV25_M252_HE/,
    "IFV-25 Бушмастер ОФ",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [/^BP_IFV25_762/, "IFV-25 7.62", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_M7A3_IFV/, "M7A3", "30mm_ap.png", "vehicle_cannon"],
  [
    /^BP_Warrior_Rarden_AP/,
    "Warrior Rarden БПС",
    "30mm_ap.png",
    "vehicle_cannon",
  ],
  [
    /^BP_Warrior_Rarden_HE/,
    "Warrior Rarden ОФ",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [/^BP_Warrior_CTAS_AP/, "Warrior CTAS БПС", "30mm_ap.png", "vehicle_cannon"],
  [
    /^BP_Warrior_CTAS_762/,
    "Warrior CTAS 7.62",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_Warrior_762/, "Warrior 7.62", "coaxialmachinegun.png", "vehicle_mg"],
  [
    /^BP_Scimitar_Rarden_AP/,
    "Scimitar Rarden БПС",
    "30mm_ap.png",
    "vehicle_cannon",
  ],
  [
    /^BP_Scimitar_Rarden_HE/,
    "Scimitar Rarden ОФ",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [/^BP_Scimitar_762/, "Scimitar 7.62", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_CROWS_M2_Stryker/, "Stryker CROWS M2", "m2browning.png", "vehicle_mg"],
  [
    /^BP_CROWS_M240_Stryker/,
    "Stryker CROWS M240",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_M1126_CROWS_M2/, "M1126 CROWS M2", "m2browning.png", "vehicle_mg"],
  [
    /^BP_M1126_CROWS_M240/,
    "M1126 CROWS M240",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_M1128_/, "M1128 MGS", "tank_sabot.png", "vehicle_cannon"],
  [
    /^BP_ZBL08_ZPT-99_APFSDS/,
    "ZBL-08 30мм БПС",
    "30mm_ap.png",
    "vehicle_cannon",
  ],
  [
    /^BP_ZBL08_ZPT-99_HEFrag/,
    "ZBL-08 30мм ОФ",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [/^BP_ZBL08_QTJ02/, "ZBL-08 ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_ZBD04A_ZPT99_AP/, "ZBD-04A 30мм БПС", "30mm_ap.png", "vehicle_cannon"],
  [
    /^BP_ZBD04A_2A70_HEFrag/,
    "ZBD-04A 100мм ОФ",
    "tank_frag.png",
    "vehicle_cannon",
  ],
  [
    /^BP_ZBD04A_2A70_coax/,
    "ZBD-04A Спарка",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [
    /^BP_ZBD05_ZPT-99_APFSDS/,
    "ZBD-05 30мм БПС",
    "30mm_ap.png",
    "vehicle_cannon",
  ],
  [/^BP_ZBD05_ZPT-99_HE/, "ZBD-05 30мм ОФ", "30mm_he.png", "vehicle_cannon"],
  [/^BP_ZBD05_QTJ02/, "ZBD-05 ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [
    /^BP_ZTD05_ZPL-98A_AP/,
    "ZTD-05 105мм БПС",
    "tank_sabot.png",
    "vehicle_cannon",
  ],
  [/^BP_ZTD05_coax/, "ZTD-05 Спарка", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_ZSL10_QJZ-89/, "ZSL-10 QJZ-89", "nsv.png", "vehicle_mg"],
  [/^BP_ZSD05_QJZ-89/, "ZSD-05 QJZ-89", "nsv.png", "vehicle_mg"],
  [/^BP_MTLB_NSV/, "МТЛБ НСВ", "nsv.png", "vehicle_mg"],
  [/^BP_MTLB_PKT/, "МТЛБ ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_MTLB_30mm_AP/, "МТЛБ 30мм БПС", "30mm_ap.png", "vehicle_cannon"],
  [/^BP_MTLB30mm_PKT/, "МТЛБ 30мм ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_MTLBM_6MA/, "МТЛБ-6МА", "30mm_he.png", "vehicle_cannon"],
  [/^BP_AAVP7A1_M2/, "AAVP7A1 M2", "m2browning.png", "vehicle_mg"],
  [/^BP_FV432_RWS/, "FV432 RWS", "m2browning.png", "vehicle_mg"],
  [/^BP_M2a1Browning_FV432/, "FV432 M2", "m2browning.png", "vehicle_mg"],
  [/^BP_M2A1Browning_FV432/, "FV432 M2", "m2browning.png", "vehicle_mg"],
  [/^BP_M113A3_M2/, "M113 M2", "m2browning.png", "vehicle_mg"],
  [/^BP_BTR80_RUS_KPVT/, "БТР-80 КПВТ", "14_5mm_ap.png", "vehicle_cannon"],
  [/^BP_BTR80_RUS_PKT/, "БТР-80 ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_BTR80_MEA_KPVT/, "БТР-80 MEA КПВТ", "14_5mm_ap.png", "vehicle_cannon"],
  [
    /^BP_BTR80_MEA_PKT/,
    "БТР-80 MEA ПКТ",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [
    /^BP_BTR80_Militia_KPVT/,
    "БТР-80 МИЛ КПВТ",
    "14_5mm_ap.png",
    "vehicle_cannon",
  ],
  [
    /^BP_BTR80_Militia_PKT/,
    "БТР-80 МИЛ ПКТ",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_BTR80_INS_KPVT/, "БТР-80 ИНС КПВТ", "14_5mm_ap.png", "vehicle_cannon"],
  [
    /^BP_BTR80_INS_PKT/,
    "БТР-80 ИНС ПКТ",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_BTR80_GFI_KPVT/, "БТР-80 GFI КПВТ", "14_5mm_ap.png", "vehicle_cannon"],
  [
    /^BP_BTR80_GFI_PKT/,
    "БТР-80 GFI ПКТ",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [
    /^BP_BRDM2_KPVT_Insurgents/,
    "БРДМ-2 КПВТ",
    "14_5mm_ap.png",
    "vehicle_cannon",
  ],
  [
    /^BP_BRDM2_PKT_Insurgents/,
    "БРДМ-2 ПКТ",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_BRDM2_RUS_KPVT/, "БРДМ-2 КПВТ", "14_5mm_ap.png", "vehicle_cannon"],
  [/^BP_BRDM2_RUS_PKT/, "БРДМ-2 ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_BRDM2_MIL_KPVT/, "БРДМ-2 МИЛ КПВТ", "14_5mm_ap.png", "vehicle_cannon"],
  [
    /^BP_BRDM2_MIL_PKT/,
    "БРДМ-2 МИЛ ПКТ",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_BRDM2_INS_KPVT/, "БРДМ-2 ИНС КПВТ", "14_5mm_ap.png", "vehicle_cannon"],
  [
    /^BP_BRDM2_INS_PKT/,
    "БРДМ-2 ИНС ПКТ",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_BRDM2_AFU_KPVT/, "БРДМ-2 ВСУ КПВТ", "14_5mm_ap.png", "vehicle_cannon"],
  [
    /^BP_BRDM2_AFU_PKT/,
    "БРДМ-2 ВСУ ПКТ",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_BRDM2_GFI_KPVT/, "БРДМ-2 GFI КПВТ", "14_5mm_ap.png", "vehicle_cannon"],
  [
    /^BP_BRDM2_GFI_PKT/,
    "БРДМ-2 GFI ПКТ",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_BTRMDM_Bow_PKT/, "БТР-МДМ ПКТ", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_BTRMDM_PKT_RWS/, "БТР-МДМ RWS", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_KPVT_UB32/, "КПВТ на УБ-32", "14_5mm_ap.png", "vehicle_cannon"],
  [/^BP_CROWS_M2_Woodland/, "CROWS M2", "m2browning.png", "vehicle_mg"],
  [/^BP_CROWS_M2/, "CROWS M2", "m2browning.png", "vehicle_mg"],
  [/^BP_M1117_M2/, "M1117 M2", "m2browning.png", "vehicle_mg"],
  [/^BP_Arbalet_Kord/, "Арбалет КОРД", "kord.png", "vehicle_mg"],
  [/^BP_PK_RWS_Gun/, "ПК RWS", "nsv.png", "vehicle_mg"],
  [/^BP_PMV_RWS_M2/, "PMV RWS M2", "m2browning.png", "vehicle_mg"],
  [/^BP_PMV_Mag58_Weapon/, "PMV Mag58", "mag58.png", "vehicle_mg"],
  [/^BP_Kord_Tigr/, "Тигр КОРД", "kord.png", "vehicle_mg"],
  [/^BP_Kord_Safir_Weapon/, "Сафир КОРД", "kord.png", "vehicle_mg"],
  [/^BP_Kord_Safir$/, "Сафир КОРД", "kord.png", "vehicle_mg"],
  [/^BP_Kord_Cupola_Weapon/, "КОРД Купола", "kord.png", "vehicle_mg"],
  [/^BP_Kord_BTR-D/, "БТР-Д КОРД", "kord.png", "vehicle_mg"],
  [/^BP_Kord_Kozak/, "Козак КОРД", "kord.png", "vehicle_mg"],
  [/^BP_50Cal_M1151/, "M1151 M2 .50", "m2browning.png", "vehicle_mg"],
  [/^BP_50Cal_LUVW/, "LUVW M2 .50", "m2browning.png", "vehicle_mg"],
  [/^BP_C6_LUVW/, "LUVW C6", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_C6_Commander/, "C6 Командир", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_C16_C6/, "C16 C6", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_EnforcerRWS_M2/, "Enforcer RWS M2", "m2browning.png", "vehicle_mg"],
  [
    /^BP_EnforcerRWS_L37A2/,
    "Enforcer RWS L37A2",
    "coaxialmachinegun.png",
    "vehicle_mg",
  ],
  [/^BP_LPPV_M2RWS/, "LPPV M2 RWS", "m2browning.png", "vehicle_mg"],
  [/^BP_TLAV_M2/, "TLAV M2", "m2browning.png", "vehicle_mg"],
  [/^BP_TLAV_M240/, "TLAV M240", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_TAPV_CROWS_M2/, "TAPV CROWS M2", "m2browning.png", "vehicle_mg"],
  [/^BP_TAPV_CROWS_C6/, "TAPV CROWS C6", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_QJZ89_RWS/, "QJZ-89 RWS", "nsv.png", "vehicle_mg"],
  [/^BP_QJZ89_CSK131/, "CSK-131 QJZ-89", "nsv.png", "vehicle_mg"],
  [/^BP_QJZ89_CTM131/, "CTM-131 QJZ-89", "nsv.png", "vehicle_mg"],
  [/^BP_QJY88_CSK131_Weapon/, "CSK-131 QJY-88", "nsv.png", "vehicle_mg"],
  [/^BP_Cupola_QJZ89/, "QJZ-89 Купола", "nsv.png", "vehicle_mg"],
  [/^BP_SancakRWS_M2/, "Sancak RWS M2", "m2browning.png", "vehicle_mg"],
  [/^BP_CobraRWS_M2/, "Cobra RWS M2", "m2browning.png", "vehicle_mg"],
  [/^BP_CobraRWS_MG3/, "Cobra RWS MG3", "mg3.png", "vehicle_mg"],
  [
    /^BP_Cobra_II_OpenTurret_M2_Weapon/,
    "Cobra II M2",
    "m2browning.png",
    "vehicle_mg",
  ],
  [
    /^BP_ACV15_OpenTurret_M2_Weapon/,
    "ACV-15 M2",
    "m2browning.png",
    "vehicle_mg",
  ],
  [/^BP_ACV15_OpenTurret_MG3_Weapon/, "ACV-15 MG3", "mg3.png", "vehicle_mg"],
  [/^BP_ACV_762/, "ACV 7.62", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_PARS3_M2/, "PARS M2", "m2browning.png", "vehicle_mg"],
  [/^BP_M1151_Technical_DShK/, "M1151 ДШК", "dshk.png", "vehicle_mg"],
  [/^BP_M2_Technical/, "Техничка M2", "m2browning.png", "vehicle_mg"],
  [/^BP_DShK_Technical/, "Техничка ДШК", "dshk.png", "vehicle_mg"],
  [/^BP_M2_RHIB_Weapon/, "RHIB M2", "m2browning.png", "vehicle_mg"],
  [/^BP_M240_RHIB_Weapon/, "RHIB M240", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_NSV_RHIB_Weapon/, "RHIB НСВ", "nsv.png", "vehicle_mg"],
  [/^BP_QJZ-89_RHIB_Weapon/, "RHIB QJZ-89", "nsv.png", "vehicle_mg"],
  [/^BP_GPMG/, "GPMG", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_EmplacedDshk/, "Станковый ДШК", "dshk.png", "emplaced"],
  [/^BP_EmplacedKord/, "Станковый КОРД", "kord.png", "emplaced"],
  [/^BP_EmplacedM2_Weapon/, "Станковый M2", "m2browning.png", "emplaced"],
  [/^BP_EmplacedQJZ-89/, "Станковый QJZ-89", "nsv.png", "emplaced"],
  [/^BP_EmplacedUB32/, "Станковый УБ-32", "s5rocket.png", "emplaced"],
  [/^BP_Emplaced_ZU23/, "ЗУ-23-2", "30mm_he.png", "emplaced"],
  [/^BP_M240G_MGO/, "M240G MGO", "coaxialmachinegun.png", "vehicle_mg"],
  [/^BP_40MM_MK19_Proj/, "MK19 40мм", "T_MK19.png", "vehicle_cannon"],
  [/^BP_AGS30_40MM_VOG_Proj/, "АГС-30", "40mmhedp.png", "vehicle_cannon"],
  [/^BP_35MM_Proj_QLZ87/, "QLZ-87 35мм", "40mmhedp.png", "vehicle_cannon"],
  [/^BP_30mm_VOG19_Proj/, "Козак АГС", "40mmhedp.png", "vehicle_cannon"],
  [/^BP_Kornet_Proj/, "Корнет ПТУР", "kornet.png", "vehicle_atgm"],
  [/^BP_Konkurs_Proj/, "Конкурс ПТУР", "kornet.png", "vehicle_atgm"],
  [/^BP_Refleks_Proj/, "Рефлекс ПТУР", "kornet.png", "vehicle_atgm"],
  [/^BP_AT3_Proj/, "AT-3 ПТУР", "kornet.png", "vehicle_atgm"],
  [/^BP_BGM71TOW_Proj/, "TOW ПТУР", "bgm71_tow.png", "vehicle_atgm"],
  [/^BP_TOW_Proj/, "TOW ПТУР", "bgm71_tow.png", "vehicle_atgm"],
  [/^BP_HJ73_Proj/, "HJ-73 ПТУР", "kornet.png", "vehicle_atgm"],
  [/^BP_HJ-8ATGM_Proj/, "HJ-8 ПТУР", "kornet.png", "vehicle_atgm"],
  [/^BP_MILAN_Proj/, "MILAN ПТУР", "kornet.png", "vehicle_atgm"],
  [/^BP_SPG9_pg9v_Heat_Proj/, "СПГ-9 Кум.", "rpg7heat.png", "vehicle_cannon"],
  [
    /^BP_SPG9_og9v_Frag_Proj/,
    "СПГ-9 Осколочный",
    "rpg7frag.png",
    "vehicle_cannon",
  ],
  [/^BP_SPG9_Frag/, "СПГ-9 Осколочный", "rpg7frag.png", "vehicle_cannon"],
  [/^BP_S5_Proj/, "С-5 Ракеты", "s5rocket.png", "heli_weapon"],
  [/^BP_S8_Proj/, "С-8 Ракеты", "s5rocket.png", "heli_weapon"],
  [/^BP_Hydra70_Proj/, "Hydra 70", "T_Hydra70_HE.png", "heli_weapon"],
  [/^BP_APKWS_Proj/, "APKWS", "T_Hydra70_HEAT.png", "heli_weapon"],
  [
    /^BP_Projectile_500lb_Bomb/,
    "500lb Бомба",
    "T_Hydra70_HE.png",
    "heli_weapon",
  ],
  [/^BP_M134_Weapon/, "M134 Minigun", "T_M134.png", "heli_weapon"],
  [/^BP_M134_Loach/, "Loach M134", "T_M134_Dual.png", "heli_weapon"],
  [
    /^BP_M240H_DoorGun/,
    "M240H Бортовой",
    "coaxialmachinegun.png",
    "heli_weapon",
  ],
  [
    /^BP_M240H_UH1Y_DoorGun/,
    "UH-1Y M240H",
    "coaxialmachinegun.png",
    "heli_weapon",
  ],
  [
    /^BP_M240H_WPMC_DoorGun/,
    "WPMC M240H",
    "coaxialmachinegun.png",
    "heli_weapon",
  ],
  [/^BP_PKP_DoorGun/, "ПКП Бортовой", "pkp.png", "heli_weapon"],
  [/^BP_C6A1_DoorGun/, "C6A1 Бортовой", "coaxialmachinegun.png", "heli_weapon"],
  [/^BP_C6A1$/, "C6A1", "coaxialmachinegun.png", "heli_weapon"],
  [/^BP_MRH90_Mag58/, "MRH-90 Mag58", "mag58.png", "heli_weapon"],
  [/^BP_MG3_DoorGun/, "MG3 Бортовой", "mg3.png", "heli_weapon"],
  [
    /^BP_Mag58_Doorgun_Turret_MRH90/,
    "MRH-90 Mag58",
    "mag58.png",
    "heli_weapon",
  ],
  [/^BP_GAU21_UH1Y/, "UH-1Y GAU-21", "m2browning.png", "heli_weapon"],
  [/^BP_M134_UH1Y/, "UH-1Y M134", "T_M134.png", "heli_weapon"],
  [/^BP_Ural_375_ZU23/, "Урал ЗУ-23-2", "30mm_he.png", "vehicle_cannon"],
  [/^BP_MTLB_ZU23/, "МТЛБ ЗУ-23-2", "30mm_he.png", "vehicle_cannon"],
  [
    /^BP_ZU23_Turret_Technical/,
    "Техничка ЗУ-23-2",
    "30mm_he.png",
    "vehicle_cannon",
  ],
  [/^BP_AK74M/, "АК-74М", "ak74m.png", "rifle"],
  [/^BP_AK74GP25_Rifle/, "АК-74 ГП-25", "ak74gp25.png", "rifle"],
  [/^BP_AK74MGP25/, "АК-74М ГП-25", "ak74mgp25.png", "rifle"],
  [/^BP_AK74_/, "АК-74", "ak74.png", "rifle"],
  [/^BP_AK74$/, "АК-74", "ak74.png", "rifle"],
  [/^BP_AK12GP25/, "АК-12 ГП-25", "ak12gp25.png", "rifle"],
  [/^BP_AK12/, "АК-12", "ak12.png", "rifle"],
  [/^BP_AKS74U/, "АКС-74У", "aks74u.png", "rifle"],
  [/^BP_AKS74_/, "АКС-74", "aks74.png", "rifle"],
  [/^BP_AKS74M/, "АКС-74М", "aks74m.png", "rifle"],
  [/^BP_AKMS/, "АКМС", "akms.png", "rifle"],
  [/^BP_AKMGP25/, "АКМ ГП-25", "akmgp25.png", "rifle"],
  [/^BP_AKM/, "АКМ", "akm.png", "rifle"],
  [/^BP_AK101/, "АК-101", "ak74m.png", "rifle"],
  [/^BP_AMD65/, "AMD-65", "amd65.png", "rifle"],
  [/^BP_Ppsh41/, "ППШ-41", "ppsh-41.png", "rifle"],
  [/^BP_PMMD63/, "PMmd.63", "pmmd63.png", "rifle"],
  [/^BP_RPD/, "РПД", "rpd.png", "mg"],
  [/^BP_M4M203_Rifle/, "M4 M203", "m4_m203_acog.png", "rifle"],
  [/^BP_M4A1/, "M4A1", "m4a1.png", "rifle"],
  [/^BP_M4_SimonOffense/, "M4 WPMC", "m4.png", "rifle"],
  [/^BP_M4_Wormpool/, "M4 WPMC", "m4.png", "rifle"],
  [/^BP_M4_Classic/, "M4 Classic", "m4.png", "rifle"],
  [/^BP_M4_/, "M4", "m4.png", "rifle"],
  [/^BP_M4$/, "M4", "m4.png", "rifle"],
  [/^BP_M16A4M203/, "M16A4 M203", "m16a4m203.png", "rifle"],
  [/^BP_M16A2M203/, "M16A2 M203", "m16a4m203.png", "rifle"],
  [/^BP_M16A4/, "M16A4", "M16A4.png", "rifle"],
  [/^BP_M16A2/, "M16A2", "m16a2.png", "rifle"],
  [/^BP_M16_Wormpool/, "M16 WPMC", "M16A4.png", "rifle"],
  [/^BP_M27_IAR/, "M27 IAR", "m27.png", "mg"],
  [/^BP_M27_Optic/, "M27", "m27.png", "rifle"],
  [/^BP_M27_Bipod/, "M27", "m27.png", "rifle"],
  [/^BP_M27$/, "M27", "m27.png", "rifle"],
  [/^BP_L85A2AG36/, "L85A2 AG36", "l85a2ag36.png", "rifle"],
  [/^BP_L85A2/, "L85A2", "l85a2.png", "rifle"],
  [/^BP_L86A2/, "L86A2 LSW", "l86a2.png", "mg"],
  [/^BP_L22A2/, "L22A2", "l22a2.png", "rifle"],
  [/^BP_L129A1/, "L129A1", "l129a1.png", "dmr"],
  [/^BP_L110A2/, "L110A2 Minimi", "l110a2.png", "mg"],
  [/^BP_L119A1/, "L119A1", "l85a2.png", "rifle"],
  [/^BP_EF88C/, "EF88C", "EF88.png", "rifle"],
  [/^BP_EF88/, "EF88", "EF88.png", "rifle"],
  [/^BP_F89/, "F89 Minimi", "f89.png", "mg"],
  [/^BP_F88/, "F88", "F88.png", "rifle"],
  [/^BP_Maximi/, "Maximi", "maximi.png", "mg"],
  [/^BP_C8A3.*M203/, "C8A3 M203", "C8A3M203C79A2.png", "rifle"],
  [/^BP_C8A3/, "C8A3", "c8a3.png", "rifle"],
  [/^BP_C7A2.*M203/, "C7A2 M203", "c7a2_c79a2_foregrip.png", "rifle"],
  [/^BP_C7A2/, "C7A2", "c7a2.png", "rifle"],
  [/^BP_C9A2/, "C9A2", "C9A2.png", "mg"],
  [/^BP_C14/, "C14 Timberwolf", "C14.png", "sniper"],
  [/^BP_QBZ95-1_QLG-10/, "QBZ-95-1 QLG-10", "qbz95-1.png", "rifle"],
  [/^BP_QBZ95-1/, "QBZ-95-1", "qbz95-1.png", "rifle"],
  [/^BP_QBZ95B/, "QBZ-95B", "qbz95b.png", "rifle"],
  [/^BP_QBZ191/, "QBZ-191", "qbz95-1.png", "rifle"],
  [/^BP_QBZ192/, "QBZ-192", "qbz95-1.png", "rifle"],
  [/^BP_QBU-88/, "QBU-88", "qbu-88.png", "dmr"],
  [/^BP_QBU-191/, "QBU-191", "qbu-88.png", "dmr"],
  [/^BP_QJY-88/, "QJY-88", "qjy-88.png", "mg"],
  [/^BP_QJB95-1/, "QJB-95-1 LSW", "qjb95-1.png", "mg"],
  [/^BP_QCW05/, "QCW-05", "qbz95-1.png", "smg"],
  [/^BP_G3A3HK79/, "G3A3 HK79", "g3a3hk79.png", "rifle"],
  [/^BP_G3A3_Drum/, "G3A3 Drum", "g3a3.png", "rifle"],
  [/^BP_G3A3/, "G3A3", "g3a3.png", "rifle"],
  [/^BP_G3A4/, "G3A4", "g3a4.png", "rifle"],
  [/^BP_G3KA4/, "G3KA4", "g3ka4.png", "rifle"],
  [/^BP_G3SG1/, "G3SG1", "g3sg1.png", "dmr"],
  [/^BP_MG3/, "MG3", "mg3.png", "mg"],
  [/^BP_MPT76/, "MPT-76", "mpt76.png", "rifle"],
  [/^BP_MPT9/, "MPT-9", "mpt76.png", "rifle"],
  [/^BP_PMT76/, "MPT-76", "mpt76.png", "rifle"],
  [/^BP_SAR109T/, "SAR-109T", "sar109t.png", "smg"],
  [/^BP_SOR109T/, "SAR-109T", "sar109t.png", "smg"],
  [/^BP_KNT76/, "KNT-76", "mpt76.png", "dmr"],
  [/^BP_SVDM/, "СВДМ", "svdm.png", "dmr"],
  [/^BP_SVD/, "СВД", "svd.png", "dmr"],
  [/^BP_SV98M/, "СВ-98М", "sv98m.png", "sniper"],
  [/^BP_SV98/, "СВ-98", "sv98m.png", "sniper"],
  [/^BP_ASVAL/, "АС Вал", "asval.png", "rifle"],
  [/^BP_VSS/, "ВСС Винторез", "asval.png", "dmr"],
  [/^BP_Mosin_M1891_Sniper/, "Мосин Снайпер", "mosin_sniper.png", "sniper"],
  [/^BP_Mosin_M38/, "Мосин M38", "mosin_carbine.png", "rifle"],
  [/^BP_Mosin_M1891/, "Мосинка", "mosinm1891.png", "rifle"],
  [/^BP_Mosin/, "Мосинка", "mosinm1891.png", "rifle"],
  [/^BP_SKS_Optic/, "СКС", "sks_pu.png", "dmr"],
  [/^BP_SKSTazco/, "СКС Tazco", "sks.png", "dmr"],
  [/^BP_SKS/, "СКС", "sks.png", "rifle"],
  [/^BP_M110/, "M110 SASS", "m110.png", "dmr"],
  [/^BP_M38_DMR/, "M38 DMR", "m38.png", "dmr"],
  [/^BP_M39/, "M39 EMR", "m39.png", "dmr"],
  [/^BP_M21/, "M21", "m110.png", "dmr"],
  [/^BP_TW_338_SWS/, "TW .338 SWS", "C14.png", "sniper"],
  [/^BP_M14_Optics/, "M14 EBR", "m14.png", "dmr"],
  [/^BP_M14_M68/, "M14", "m14.png", "rifle"],
  [/^BP_M14$/, "M14", "m14.png", "rifle"],
  [/^BP_M14_/, "M14", "m14.png", "rifle"],
  [/^BP_M1Carbine/, "M1 Carbine", "m14.png", "rifle"],
  [/^BP_HK417/, "HK417", "HK417.png", "dmr"],
  [/^BP_HK416/, "HK416", "HK417.png", "rifle"],
  [/^BP_HK51/, "HK51", "hk51.png", "rifle"],
  [/^BP_FNFAL_GL/, "FN FAL GL", "fnfal.png", "rifle"],
  [/^BP_FNFAL/, "FN FAL", "fnfal.png", "rifle"],
  [/^BP_LeeEnfield/, "Lee-Enfield", "mosinm1891.png", "rifle"],
  [/^BP_UAR-10/, "UAR-10", "m110.png", "dmr"],
  [/^BP_Malyuk/, "Малюк", "ak74m.png", "rifle"],
  [/^BP_AUG/, "AUG", "EF88.png", "rifle"],
  [/^BP_RPK74M/, "РПК-74М", "rpk74m.png", "mg"],
  [/^BP_RPK74/, "РПК-74", "rpk74.png", "mg"],
  [/^BP_RPK/, "РПК", "rpk.png", "mg"],
  [/^BP_PKP/, "ПКП Печенег", "pkp.png", "mg"],
  [/^BP_PKM/, "ПКМ", "pkm.png", "mg"],
  [/^BP_M249_Classic/, "M249", "m249.png", "mg"],
  [/^BP_M249_Pip/, "M249 PIP", "m249pip.png", "mg"],
  [/^BP_M249/, "M249", "m249.png", "mg"],
  [/^BP_M240_M145/, "M240B", "m240b.png", "mg"],
  [/^BP_M240_MGO/, "M240G MGO", "m240g.png", "mg"],
  [/^BP_M240$/, "M240", "m240b.png", "mg"],
  [/^BP_Minimi/, "Minimi", "minimi.png", "mg"],
  [/^BP_MP5A3/, "MP5A3", "mp5a3.png", "smg"],
  [/^BP_Vz61/, "Vz.61 Škorpion", "vz61.png", "smg"],
  [/^BP_MP443/, "МП-443 Грач", "mp443.png", "pistol"],
  [/^BP_M9A1/, "M9A1", "m9a1beretta.png", "pistol"],
  [/^BP_M9$/, "M9", "m9a1beretta.png", "pistol"],
  [/^BP_M17MHS/, "M17 MHS", "m17mhs.png", "pistol"],
  [/^BP_Makarov/, "Макаров", "makarov.png", "pistol"],
  [/^BP_TT33/, "ТТ-33", "tt33.png", "pistol"],
  [/^BP_BrowningHP/, "Browning HP", "browninghp.png", "pistol"],
  [/^BP_Browning_P35/, "Browning P35", "browninghp.png", "pistol"],
  [/^BP_G17/, "Glock 17", "glock17.png", "pistol"],
  [/^BP_QSZ-92/, "QSZ-92", "qsz92.png", "pistol"],
  [/^BP_QSZ92/, "QSZ-92", "qsz92.png", "pistol"],
  [/^BP_L131A1/, "L131A1", "glock17.png", "pistol"],
  [/^BP_RPG7_Heat_Proj/, "РПГ-7 Кум.", "rpg7heat.png", "launcher"],
  [/^BP_RPG7_Tandem_Heat/, "РПГ-7 Тандем", "rpg7tandem.png", "launcher"],
  [/^BP_RPG7_Frag_Proj/, "РПГ-7 Осколочный", "rpg7frag.png", "launcher"],
  [/^BP_RPG7_Frag_5Mag/, "РПГ-7 Осколочный", "rpg7frag.png", "launcher"],
  [/^BP_RPG29/, "РПГ-29", "rpg29.png", "launcher"],
  [/^BP_RPG28/, "РПГ-28", "rpg28.png", "launcher"],
  [/^BP_RPG26/, "РПГ-26", "rpg26.png", "launcher"],
  [/^BP_PF-98_Tandem/, "PF-98 Тандем", "pf98.png", "launcher"],
  [/^BP_PF-98_HE/, "PF-98 ОФ", "pf98.png", "launcher"],
  [/^BP_DZJ-08/, "DZJ-08", "pf98.png", "launcher"],
  [/^BP_M72A7/, "M72 LAW", "m72law.png", "launcher"],
  [/^BP_M72A6/, "M72 LAW", "m72law.png", "launcher"],
  [/^BP_AT4_Rocket/, "AT-4", "at4.png", "launcher"],
  [/^BP_M136AT4/, "M136 AT-4", "at4.png", "launcher"],
  [/^BP_M3MAAWS_Tandem/, "Carl Gustaf Тандем", "carlgustavm2.png", "launcher"],
  [/^BP_M3MAAWS_Heat/, "Carl Gustaf Кум.", "carlgustavm2.png", "launcher"],
  [
    /^BP_CarlGustavM2_FFV751/,
    "Carl Gustaf 751",
    "carlgustavm2.png",
    "launcher",
  ],
  [
    /^BP_CarlGustavM2_FFV441D/,
    "Carl Gustaf 441",
    "carlgustavm2.png",
    "launcher",
  ],
  [/^BP_FFV751_Tandem/, "Carl Gustaf 751", "carlgustavm2.png", "launcher"],
  [/^BP_FFV551_Rocket/, "Carl Gustaf 551", "carlgustavm2.png", "launcher"],
  [/^BP_SMAW_Tandem/, "SMAW Тандем", "smaw_tandem.png", "launcher"],
  [/^BP_SMAW_Heat/, "SMAW Кум.", "smaw_heat.png", "launcher"],
  [
    /^BP_SMAW_SpottingRifle/,
    "SMAW Пристрелочная",
    "smaw_spottingrifle.png",
    "launcher",
  ],
  [/^BP_NLAW/, "NLAW", "nlaw.png", "launcher"],
  [/^BP_C90_Rocket/, "C90", "at4.png", "launcher"],
  [/^BP_HAR66/, "HAR-66", "at4.png", "launcher"],
  [/^BP_40MM_Proj/, "ГП 40мм", "gp25.png", "grenade"],
  [/^BP_40MM_VOG_Proj/, "ВОГ-25", "gp25.png", "grenade"],
  [
    /^BP_Projectile_RifleGrenade_FNFAL/,
    "FAL Ружейная граната",
    "rpg7frag.png",
    "grenade",
  ],
  [/^BP_M67Frag/, "M67", "m67.png", "grenade"],
  [/^BP_F1Frag_au/, "F1 (Австралия)", "adff1frag.png", "grenade"],
  [/^BP_F1Frag/, "Ф-1", "f1.png", "grenade"],
  [/^BP_RGD5Frag/, "РГД-5", "rgd5.png", "grenade"],
  [/^BP_RGOFrag/, "РГО", "rgd5.png", "grenade"],
  [/^BP_L109A1Frag/, "L109A1", "l109a1.png", "grenade"],
  [/^BP_C13Frag/, "C13", "l109a1.png", "grenade"],
  [/^BP_Type86p_Frag/, "Type 86P", "type86p.png", "grenade"],
  [/^BP_RKG3Antitank/, "РКГ-3", "rkg3.png", "grenade"],
  [/^BP_Proj_RKG3/, "РКГ-3", "rkg3.png", "grenade"],
  [/^BP_SOCP_Knife/, "Нож SOCP", "socp.png", "melee"],
  [/^BP_AK74Bayonet/, "Штык АК-74", "ak74_bayonet.png", "melee"],
  [/^BP_AKMBayonet/, "Штык АКМ", "akm_bayonet.png", "melee"],
  [/^BP_M9Bayonet/, "Штык M9", "m9_bayonet.png", "melee"],
  [/^BP_G3Bayonet/, "Штык G3", "g3_bayonet.png", "melee"],
  [/^BP_Bayonet2000/, "Штык 2000", "sa80_bayonet.png", "melee"],
  [/^BP_SA80Bayonet/, "Штык SA80", "sa80_bayonet.png", "melee"],
  [/^BP_QNL-95_Bayonet/, "Штык QNL-95", "sks_bayonet.png", "melee"],
  [/^BP_OKC-3S/, "Нож OKC-3S", "okc-3s.png", "melee"],
  [/^BP_KLT/, "KLT", "okc-3s.png", "melee"],
  [/^BP_KLS/, "KLS", "okc-3s.png", "melee"],
  [/^BP_KLF/, "KLF", "okc-3s.png", "melee"],
  [/^BP_SOR9/, "SOR9", "okc-3s.png", "melee"],
  [/^BP_Deployable_TM62Mine/, "ТМ-62 Мина", "tm62_mine.png", "deployable"],
  [/^BP_Deployable_M15Mine/, "M15 Мина", "m15_mine.png", "deployable"],
  [/^BP_Deployable_Type72Mine/, "Type 72 Мина", "m15_mine.png", "deployable"],
  [/^BP_Deployable_IED/, "СВУ", "IED.png", "deployable"],
  [/^BP_Deployable_M112/, "C4", "T_m112_c4explosive_timed.png", "deployable"],
  [
    /^BP_Deployable_TNT_600g/,
    "ТНТ 600г",
    "tnt_600g_explosive.png",
    "deployable",
  ],
  [/^BP_Deployable_TNT_1lb/, "ТНТ 1lb", "tnt_1lb_explosive.png", "deployable"],
  [/^BP_Deployable_SZ1/, "SZ-1", "sz1_explosive.png", "deployable"],
  [/^BP_Deployable_CompB/, "Comp B", "COMPB.png", "deployable"],
  [
    /^BP_Deployable_SensitiveExplosives/,
    "Bangerite",
    "Bangerite.png",
    "deployable",
  ],
  [/^BP_PLA_Deployable_TNT/, "PLA ТНТ", "tnt_600g_explosive.png", "deployable"],
];

export function resolveWeapon(key) {
  if (isTrash(key)) return null;

  for (const [pattern, group, image, category] of WEAPON_RULES) {
    if (pattern.test(key)) {
      return { group, image, category };
    }
  }

  const cleaned = key
    .replace(/^BP_/, "")
    .replace(/_C_\d+$/, "")
    .replace(/_/g, " ");
  return { group: cleaned, image: null, category: "unknown" };
}

export function groupWeapons(weapons) {
  const grouped = {};

  for (const [key, value] of Object.entries(weapons)) {
    const resolved = resolveWeapon(key);
    if (!resolved) continue;

    const { group, image, category } = resolved;
    if (!grouped[group]) {
      grouped[group] = { kills: 0, image, category };
    }
    grouped[group].kills += value;
    if (!grouped[group].image && image) {
      grouped[group].image = image;
    }
  }

  return Object.entries(grouped)
    .map(([group, data]) => ({
      group,
      kills: data.kills,
      image: data.image,
      category: data.category,
    }))
    .sort((a, b) => b.kills - a.kills);
}

const VEHICLE_CATEGORIES = new Set([
  "vehicle_mg",
  "vehicle_cannon",
  "vehicle_atgm",
  "vehicle_arty",
  "heli_weapon",
  "emplaced",
]);

export function calcVehicleKillsFromGrouped(groupedWeapons) {
  return groupedWeapons
    .filter((w) => VEHICLE_CATEGORIES.has(w.category))
    .reduce((sum, w) => sum + w.kills, 0);
}

export function calcArtilleryKills(groupedWeapons) {
  return groupedWeapons
    .filter((w) => w.category === "vehicle_arty" || w.category === "mortar")
    .reduce((sum, w) => sum + w.kills, 0);
}

export function calcKnifeKills(groupedWeapons) {
  return groupedWeapons
    .filter((w) => w.category === "melee")
    .reduce((sum, w) => sum + w.kills, 0);
}

export default {
  resolveWeapon,
  groupWeapons,
  calcVehicleKillsFromGrouped,
  calcArtilleryKills,
  calcKnifeKills,
  TRASH_PATTERNS,
};
